use std::fmt::{Display, Formatter, Result};

#[derive(Debug, Clone)]
pub enum Inst {
    Beqz(Reg, String),
    Bnez(Reg, String),
    J(String),
    Call(String),
    Ret,
    Lw(Reg, i32, Reg),
    Sw(Reg, i32, Reg),
    Add(Reg, Reg, Reg),
    Addi(Reg, Reg, i32),
    Sub(Reg, Reg, Reg),
    Slt(Reg, Reg, Reg),
    Sgt(Reg, Reg, Reg),
    Seqz(Reg, Reg),
    Snez(Reg, Reg),
    Xor(Reg, Reg, Reg),
    Xori(Reg, Reg, i32),
    Or(Reg, Reg, Reg),
    Ori(Reg, Reg, i32),
    And(Reg, Reg, Reg),
    Andi(Reg, Reg, i32),
    Sll(Reg, Reg, Reg),
    Slli(Reg, Reg, i32),
    Srl(Reg, Reg, Reg),
    Sra(Reg, Reg, Reg),
    Mul(Reg, Reg, Reg),
    Div(Reg, Reg, Reg),
    Rem(Reg, Reg, Reg),
    Li(Reg, i32),
    La(Reg, String),
    Mv(Reg, Reg),
}

#[derive(Debug, Clone, Copy)]
pub enum Reg {
    Zero,
    Ra,
    Sp,
    Gp,
    Tp,
    T0,
    T1,
    T2,
    Fp,
    S1,
    A0,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    S2,
    S3,
    S4,
    S5,
    S6,
    S7,
    S8,
    S9,
    S10,
    S11,
    T3,
    T4,
    T5,
    T6,
}

impl Display for Reg {
    fn fmt(&self, f: &mut Formatter) -> Result {
        let s = match self {
            Reg::Zero => "zero",
            Reg::Ra => "ra",
            Reg::Sp => "sp",
            Reg::Gp => "gp",
            Reg::Tp => "tp",
            Reg::T0 => "t0",
            Reg::T1 => "t1",
            Reg::T2 => "t2",
            Reg::Fp => "fp",
            Reg::S1 => "s1",
            Reg::A0 => "a0",
            Reg::A1 => "a1",
            Reg::A2 => "a2",
            Reg::A3 => "a3",
            Reg::A4 => "a4",
            Reg::A5 => "a5",
            Reg::A6 => "a6",
            Reg::A7 => "a7",
            Reg::S2 => "s2",
            Reg::S3 => "s3",
            Reg::S4 => "s4",
            Reg::S5 => "s5",
            Reg::S6 => "s6",
            Reg::S7 => "s7",
            Reg::S8 => "s8",
            Reg::S9 => "s9",
            Reg::S10 => "s10",
            Reg::S11 => "s11",
            Reg::T3 => "t3",
            Reg::T4 => "t4",
            Reg::T5 => "t5",
            Reg::T6 => "t6",
        };
        write!(f, "{}", s)
    }
}
