// Copyright (C) 2024 Elkeid-me
//
// This file is part of Xenon ATC-X.
//
// Xenon ATC-X is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Xenon ATC-X is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Xenon ATC-X.  If not, see <http://www.gnu.org/licenses/>.

WHITESPACE = _{ " " | "\t" | NEWLINE }
identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

translation_unit = _{ SOI ~ global_item+ ~ EOI }

global_item = _{ all_definitions | func_decl ~ ";" | func_def }

func_def          =  { func_decl ~ block }
func_decl         =  { function_return_type ~ identifier ~ "(" ~ parameter_list ~ ")" }
parameter_list    =  { parameter_def ~ ("," ~ parameter_def)* | "void" | "" }
parameter_def     = _{ ptr_parameter | var_parameter | ptr_parameter_no_name | var_parameter_no_name }

ptr_parameter         = { int_keyword ~ identifier ~ "[" ~ "]" ~ array_lengths? }
var_parameter         = { int_keyword ~ identifier }
ptr_parameter_no_name = { int_keyword ~ "[" ~ "]" ~ array_lengths? }
var_parameter_no_name = { int_keyword }

int_keyword      = @{ "int" ~ !(ASCII_ALPHANUMERIC | "_") }
const_keyword    = @{ "const" ~ !(ASCII_ALPHANUMERIC | "_")}
void_keyword     = @{ "void" ~ !(ASCII_ALPHANUMERIC | "_") }
return_keyword   = @{ "return" ~ !(ASCII_ALPHANUMERIC | "_") }
continue_keyword = @{ "continue" ~ !(ASCII_ALPHANUMERIC | "_") }
break_keyword    = @{ "break" ~ !(ASCII_ALPHANUMERIC | "_") }

const_definition_type = _{ (const_keyword ~ int_keyword) | (int_keyword ~ const_keyword) }

function_return_type = _{ int_keyword | void_keyword }

const_definitions         = _{ const_definition_type ~ const_definition ~ ("," ~ const_definition)* }
const_definition          = _{ const_array_definition | const_variable_definition }
const_variable_definition =  { identifier ~ "=" ~ expression }
const_array_definition    =  { identifier ~ array_lengths ~ "=" ~ initializer_list }

definitions         = _{ int_keyword ~ definition ~ ("," ~ definition)* }
definition          = _{ array_definition | variable_definition }
variable_definition =  { identifier ~ ("=" ~ expression)? }
array_definition    =  { identifier ~ array_lengths ~ ("=" ~ initializer_list)? }

array_lengths = _{ array_subscript }

initializer_list      =  { "{" ~ (initializer_list_item ~ ("," ~ initializer_list_item)*)? ~ "}" }
initializer_list_item = _{ initializer_list | expression}

primary = _{ integer_hex | integer_bin | integer_oct | integer_dec | function_call | array_element | identifier | "(" ~ expression ~ ")" }
atom    = _{ prefix_operator* ~ primary ~ postfix_operator* }

postfix_operator      = _{ post_inc | post_dec }
post_inc              =  { "++" }
post_dec              =  { "--" }

prefix_operator = _{ pre_inc | pre_dec | logic_not | negative | positive | bit_not }
pre_inc         =  { "++" }
pre_dec         =  { "--" }
logic_not       =  { "!" }
negative        =  { "-" }
positive        =  { "+" }
bit_not         =  { "~" }

infix  = _{ custom | three_char_operator | two_char_operator | single_char_operator }
custom = ${ "~" ~ identifier ~ "~" }

single_char_operator = _{ mul | div | modu | add | sub | xor | and | or | grt | les | assignment | method }
two_char_operator    = _{ logic_and | logic_or | left_pipe | right_pipe | shl | sar | eq | neq
                          | geq | leq | add_assign | sub_assign | mul_assign | div_assign
                          | mod_assign | and_assign | or_assign | xor_assign }
three_char_operator  = _{ sar_assign | shl_assign }

mul  = { "*" }
div  = { "/" }
modu = { "%" }
add  = { "+" }
sub  = { "-" }

logic_and = { "&&" }
logic_or  = { "||" }

shl = { "<<" }
sar = { ">>" }
xor = { "^" }
and = { "&" }
or  = { "|" }

eq  = { "==" }
neq = { "!=" }
grt = { ">" }
geq = { ">=" }
les = { "<" }
leq = { "<=" }

assignment = { "=" }
add_assign = { "+=" }
sub_assign = { "-=" }
mul_assign = { "*=" }
div_assign = { "/=" }
mod_assign = { "%=" }
and_assign = { "&=" }
or_assign  = { "|=" }
xor_assign = { "^=" }
shl_assign = { "<<=" }
sar_assign = { ">>=" }

right_pipe = { "|>" }
left_pipe = { "<|" }

method = { "." }

array_element   = { identifier ~ array_subscript }
array_subscript = { ("[" ~ expression ~ "]")+ }

expression    =  { atom ~ (infix ~ atom)* }
function_call =  { identifier ~ "(" ~ argument_list? ~ ")" }
argument_list = _{ expression ~ ("," ~ expression)* }

return_statement = { return_keyword ~ expression? }
while_statement  = { "while" ~ "(" ~ expression ~ ")" ~ (non_block_block_item_in_if_or_while | block) }
if_statement     = { "if" ~ "(" ~ expression ~ ")" ~ (non_block_block_item_in_if_or_while | block) ~ ("else" ~ (non_block_block_item_in_if_or_while | block))? }

integer_hex = @{ ("0x" | "0X") ~ ASCII_HEX_DIGIT+ }
integer_dec = @{ ASCII_NONZERO_DIGIT ~ ASCII_DIGIT* }
// 同时解析八进制整数和 0
integer_oct = @{ "0" ~ ASCII_OCT_DIGIT* }
integer_bin = @{ ("0b" | "0B") ~ ASCII_BIN_DIGIT+ }

block = { "{" ~ (block | non_block_block_item)* ~ "}" }

statement            = _{ while_statement | if_statement | (continue_keyword | break_keyword | return_statement | expression | "") ~ ";"}
all_definitions      = _{ (const_definitions | definitions) ~ ";" }
non_block_block_item = _{ statement | all_definitions }

definitions_in_if_or_while_non_block =  { (const_definitions | definitions) ~ ";" }
empty_statement                      =  { ";" }
non_block_block_item_in_if_or_while  = _{ empty_statement | statement | definitions_in_if_or_while_non_block }
